name: Release Category_Switcher

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------------
      # 1️⃣ Category_Switcher.rar (EXE + Resources + Version + Settings)
      # -------------------------------
      - name: Pack Category_Switcher.rar
        shell: pwsh
        run: |
          $sevenZip = "C:\Program Files\7-Zip\7z.exe"
          $tempDir = "ReleasePackage"
          New-Item -ItemType Directory -Path $tempDir

          Copy-Item -Recurse -Force "Release EXE" "$tempDir\Release EXE"
          Copy-Item -Recurse -Force "Resources" "$tempDir\Resources"
          Copy-Item -Force "Version.json","settings.xaml" "$tempDir"

          & "$sevenZip" a "Category_Switcher.rar" "$tempDir\*"

          Remove-Item -Recurse -Force $tempDir

      # -------------------------------
      # 2️⃣ Category_Switcher Source.rar (alles außer Release EXE, .git, .github)
      # -------------------------------
      - name: Pack Category_Switcher Source.rar
        shell: pwsh
        run: |
          $sevenZip = "C:\Program Files\7-Zip\7z.exe"
          $tempDir = "SourcePackage"
          New-Item -ItemType Directory -Path $tempDir

          $exclude = @("Release EXE",".git",".github","*.rar")
          Get-ChildItem -Recurse -Force | Where-Object { $exclude -notcontains $_.Name } | ForEach-Object {
              $dest = Join-Path $tempDir $_.FullName.Substring((Get-Location).Path.Length + 1)
              if($_.PSIsContainer){ New-Item -ItemType Directory -Path $dest -Force } else { Copy-Item $_.FullName $dest -Force }
          }

          & "$sevenZip" a "Category_Switcher Source.rar" "$tempDir\*"

          Remove-Item -Recurse -Force $tempDir

      # -------------------------------
      # 3️⃣ GitHub Release erstellen
      # -------------------------------
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Category_Switcher.rar
            Category_Switcher Source.rar
